name: lego_piano
description: A companion app to the LEGO grand piano
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.2
  tonic: ^0.2.4
  sheet_music: ^0.3.0
  flutter_blue: ^0.8.0
  flutter_midi: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/audio/